### ISSUE TITLE
Additional OS libraries/packages needed

### ISSUE THREAD

**Issue by rbrunckhorst** [openafs-contrib/ansible-openafs#60]
Additional OS libraries/packages are needed to enable optional features in openafs.
Those features requires extra libraries, for example Jansson libs to handle JSON data.

So we should implement a way a user can specify extra packages to install to fulfill those requirements.

The most flexible way would be the user can specify a list of extra packages that will be installed on the managed instances via the openafs_devel role. This approach requires that the user knows exactly the package name(s) for the specific distribution. On the other hand it doesn't matter which packages are needed and there will not be any changes needed if package requirements changed in the future.

**Comment by rbrunckhorst** [comment]
#61

**Comment by meffie** [comment]
As you mention here, the variable name will depend on the platform (package manager), so I think this will be difficult to use and debug. After thinking about this for a bit, I think we want the devel role to install everything needed to build OpenAFS and have it sort out the platform differences automatically, otherwise it will be difficult to debug.

For example, the playbooks that build or install openafs could install the a package name depending on the ansible_package_mgr variable. If using molecule, this could be done in a prepare or converge playbook.

I think if we have a branch that we use regularly that requires a new devel library, e.g. libevent, libjson etc, we should add it to the list of packages installed by devel role, since it will not hurt to have it for old branches.

**Comment by rbrunckhorst** [comment]
The tasks will take care for the different package manager.
If there are platforms involved like debian, Solaris and redhat in one scenario the package name could be different and then the variable needs to be defined individual via hosts variable for each platform / host.

- Ralf
Am 18. Apr. 2022, 14:58 +0200 schrieb Michael Meffie ***@***.***>:

As you mention here, the variable name will depend on the platform (package manager), so I think this will be difficult to use and debug. After thinking about this for a bit, I think we want the devel role to install everything needed to build OpenAFS and have it sort out the platform differences automatically, otherwise it will be difficult to debug.

For example, the playbooks that build or install openafs could install the a package name depending on the ansible_package_mgr variable. If using molecule, this could be done in a prepare or converge playbook.

I think if we have a branch that we use regularly that requires a new devel library, e.g. libevent, libjson etc, we should add it to the list of packages installed by devel role, since it will not hurt to have it for old branches.

**Comment by meffie** [comment]
> The tasks will take care for the different package manager.

Yes, but that is the roles job. If you have tasks in a playbook outside the role that are platform specific or ansible_package_mgr you need to take care to use the right tasks for a given node. This patch seems to want to distribute that between the role and the playbook by reusing the platform specific includes from the playbook level.

> If there are platforms involved like debian, Solaris and redhat in one scenario the package name could be different and then the variable needs to be defined individual via hosts variable for each platform / host.

Yes, that is my objection. If those need to be different then they should be at the playbook level.  

At this point, I feel we should continue to add openafs devel specific package names to the install tasks with the role.  It dont think we should pass arbitrary package names as a role variable. If you need to install an arbitrary package then you can do that in a playbook, if it is needed to build openafs, the name of the packages should be included in the openafs_devel role.  It is very infrequent to add new dependencies.

I could see role variables that are platform independent, but this variable is not platform independent so "breaks" the main feature of openafs_devel, which is to deal with the platform differences.

**Comment by meffie** [comment]
> Solaris and redhat in one scenario the package name could be different

To reiterate this point, this role is not used just for molecule scenarios. The openafs_devel role is also used in regular playbooks to setup devel hosts. I commonly have an inventory of several hosts and playbooks to set them up.  If I had to add package names per host, then there is not much point in importing openafs_devel any more, I would have to go back to having per host tasks / variables, instead of just importing the role and having it install all the packages needed for a given host.

Can we just have a PR that adds the new dependency?

**Comment by rbrunckhorst** [comment]
I will work on that tomorrow.
So I will add packages to the devel role in a new PR.

**Comment by meffie** [comment]
Fixed in PR #62
